update action

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -70,135 +70,134 @@ runs:
         pip3 install --target ~/.local botocore
       shell: bash
 
-   # # concretize dependencies
-   # - name: Concretize Spack Environment Using YAML Specification
-   #   id: concretize-deps
-   #   run: |
-   #     $GITHUB_ACTION_PATH/scripts/concretize_deps.sh \
-   #       -a ${{ inputs.architecture }} \
-   #       -d $(echo "${{ inputs.dependencies }}" | awk '$1=$1' RS= OFS=,) \
-   #       -i ${{ inputs.dependencies_install_dir }} \
-   #       -r $GITHUB_WORKSPACE
-   #   shell: bash
+    # concretize dependencies
+    - name: Concretize Spack Environment Using YAML Specification
+      id: concretize-deps
+      run: |
+        $GITHUB_ACTION_PATH/scripts/concretize_deps.sh \
+          -a ${{ inputs.architecture }} \
+          -d $(echo "${{ inputs.dependencies }}" | awk '$1=$1' RS= OFS=,) \
+          -i ${{ inputs.dependencies_install_dir }} \
+          -r $GITHUB_WORKSPACE
+      shell: bash
 
-   # # restore dependencies from cache
-   # - name: Restore Dependencies
-   #   id: restore-deps 
-   #   uses: actions/cache@v3
-   #   with:
-   #     path: ${{ inputs.dependencies_install_dir }} 
-   #     key: spack-${{ runner.os }}-${{ inputs.architecture }}-${{ hashFiles('**/spack.lock') }}
-   #     restore-keys: |
-   #       spack-${{ runner.os }}-${{ inputs.architecture }}-${{ hashFiles('**/spack.lock') }}
+    # restore dependencies from cache
+    - name: Restore Dependencies
+      id: restore-deps 
+      uses: actions/cache@v3
+      with:
+        path: ${{ inputs.dependencies_install_dir }} 
+        key: spack-${{ runner.os }}-${{ inputs.architecture }}-${{ hashFiles('**/spack.lock') }}
+        restore-keys: |
+          spack-${{ runner.os }}-${{ inputs.architecture }}-${{ hashFiles('**/spack.lock') }}
 
-   # # install dependencies
-   # - name: Install Dependencies with Spack 
-   #   id: install-deps
-   #   run: |
-   #     $GITHUB_ACTION_PATH/scripts/install_deps.sh \
-   #       -r $GITHUB_WORKSPACE
-   #   shell: bash
+    # install dependencies
+    - name: Install Dependencies with Spack 
+      id: install-deps
+      run: |
+        $GITHUB_ACTION_PATH/scripts/install_deps.sh \
+          -r $GITHUB_WORKSPACE
+      shell: bash
 
-   # # checkout data models
-   # - name: Checkout CDEPS
-   #   uses: actions/checkout@v3
-   #   with:
-   #     repository: uturuncoglu/CDEPS
-   #     path: ${{ inputs.app_install_dir }}/cdeps
-   #     ref: hotfix/std_build
+    # checkout data models
+    - name: Checkout CDEPS
+      uses: actions/checkout@v3
+      with:
+        repository: uturuncoglu/CDEPS
+        path: ${{ inputs.app_install_dir }}/cdeps
+        ref: hotfix/std_build
 
-   # # build and install data models
-   # - name: Build and Install CDEPS
-   #   run: |
-   #     export PATH=${{ inputs.dependencies_install_dir }}/view/bin:$PATH
-   #     export ESMFMKFILE=${{ inputs.dependencies_install_dir }}/view/lib/esmf.mk
-   #     export FC=gfortran
-   #     cd ${{ inputs.app_install_dir }}/cdeps
-   #     mkdir build
-   #     cd build
-   #     cmake -DCMAKE_INSTALL_PREFIX=${{ inputs.app_install_dir }} \
-   #       -DPIO_C_LIBRARY=${{ inputs.dependencies_install_dir }}/view/lib \
-   #       -DPIO_C_INCLUDE_DIR=${{ inputs.dependencies_install_dir }}/view/include \
-   #       -DPIO_Fortran_LIBRARY=${{ inputs.dependencies_install_dir }}/view/lib \
-   #       -DPIO_Fortran_INCLUDE_DIR=${{ inputs.dependencies_install_dir }}/view/include \
-   #       -DCMAKE_Fortran_FLAGS="-ffree-line-length-none -fallow-argument-mismatch -fallow-invalid-boz" \
-   #       -DDISABLE_FoX=ON ../
-   #     make
-   #     make install
-   #   shell: bash
+    # build and install data models
+    - name: Build and Install CDEPS
+      run: |
+        export PATH=${{ inputs.dependencies_install_dir }}/view/bin:$PATH
+        export ESMFMKFILE=${{ inputs.dependencies_install_dir }}/view/lib/esmf.mk
+        export FC=gfortran
+        cd ${{ inputs.app_install_dir }}/cdeps
+        mkdir build
+        cd build
+        cmake -DCMAKE_INSTALL_PREFIX=${{ inputs.app_install_dir }} \
+          -DPIO_C_LIBRARY=${{ inputs.dependencies_install_dir }}/view/lib \
+          -DPIO_C_INCLUDE_DIR=${{ inputs.dependencies_install_dir }}/view/include \
+          -DPIO_Fortran_LIBRARY=${{ inputs.dependencies_install_dir }}/view/lib \
+          -DPIO_Fortran_INCLUDE_DIR=${{ inputs.dependencies_install_dir }}/view/include \
+          -DCMAKE_Fortran_FLAGS="-ffree-line-length-none -fallow-argument-mismatch -fallow-invalid-boz" \
+          -DDISABLE_FoX=ON ../
+        make
+        make install
+      shell: bash
 
-   # # build component
-   # - name: Build and Install Component
-   #   run: |
-   #     cd ${{ inputs.app_install_dir }}
-   #     echo "${{ inputs.component_build }}" >> install_comp.sh
-   #     chmod 755 install_comp.sh
-   #     ./install_comp.sh
-   #   shell: bash
+    # build component
+    - name: Build and Install Component
+      run: |
+        cd ${{ inputs.app_install_dir }}
+        echo "${{ inputs.component_build }}" >> install_comp.sh
+        chmod 755 install_comp.sh
+        ./install_comp.sh
+      shell: bash
 
-   # # use ESMX generic driver and create executable
-   # - name: Use ESMX to create executable
-   #   run: |
-   #     $GITHUB_ACTION_PATH/scripts/create_exe.sh \
-   #       -a ${{ inputs.app_install_dir }} \
-   #       -d ${{ inputs.data_component_name }} \
-   #       -i ${{ inputs.dependencies_install_dir }} \
-   #       -m ${{ inputs.component_name }} \
-   #       -n ${{ inputs.component_module_name }}
-   #   shell: bash
+    # use ESMX generic driver and create executable
+    - name: Use ESMX to create executable
+      run: |
+        $GITHUB_ACTION_PATH/scripts/create_exe.sh \
+          -a ${{ inputs.app_install_dir }} \
+          -d ${{ inputs.data_component_name }} \
+          -i ${{ inputs.dependencies_install_dir }} \
+          -m ${{ inputs.component_name }} \
+          -n ${{ inputs.component_module_name }}
+      shell: bash
 
-   # # restore input files from cache
-   # - name: Restore Input Files From Cache
-   #   id: cache-input
-   #   uses: actions/cache@v3
-   #   with:
-   #     path: ${{ inputs.cache_input_file_list }}
-   #     key: input-
-   #     restore-keys: |
-   #         input
+    # restore input files from cache
+    - name: Restore Input Files From Cache
+      id: cache-input
+      uses: actions/cache@v3
+      with:
+        path: ${{ inputs.cache_input_file_list }}
+        key: input-
+        restore-keys: |
+            input
 
-   # # create run directory and download input
-   # # no need to check the cache hit since script is able to check the existing files and not download again
-   # - name: Download Input Files
-   #   run: |
-   #     export PATH=${{ inputs.dependencies_install_dir }}/view/bin:$PATH
-   #     export PYTHONPATH=~/.local:$PYTHONPATH
-   #     if [ ! -d "${{ inputs.app_install_dir }}/run" ]; then
-   #       mkdir ${{ inputs.app_install_dir }}/run
-   #     fi
-   #     cd ${{ inputs.app_install_dir }}/run
-   #     python3 $GITHUB_ACTION_PATH/scripts/get_input.py --ifile ${{ inputs.test_definition }} 
-   #   shell: bash
+    # create run directory and download input
+    # no need to check the cache hit since script is able to check the existing files and not download again
+    - name: Download Input Files
+      run: |
+        export PATH=${{ inputs.dependencies_install_dir }}/view/bin:$PATH
+        export PYTHONPATH=~/.local:$PYTHONPATH
+        if [ ! -d "${{ inputs.app_install_dir }}/run" ]; then
+          mkdir ${{ inputs.app_install_dir }}/run
+        fi
+        cd ${{ inputs.app_install_dir }}/run
+        python3 $GITHUB_ACTION_PATH/scripts/get_input.py --ifile ${{ inputs.test_definition }} 
+      shell: bash
 
-   # # generate configuration files
-   # - name: Generate Configuration Files
-   #   run: |
-   #     export PYTHONPATH=$GITHUB_ACTION_PATH/scripts:$PYTHONPATH
-   #     export PYTHONPATH=$GITHUB_ACTION_PATH/scripts/paramgen:$PYTHONPATH 
-   #     cd ${{ inputs.app_install_dir }}/run
-   #     python3 $GITHUB_ACTION_PATH/scripts/gen_config.py --ifile ${{ inputs.test_definition }}
-   #   shell: bash
+    # generate configuration files
+    - name: Generate Configuration Files
+      run: |
+        export PYTHONPATH=$GITHUB_ACTION_PATH/scripts:$PYTHONPATH
+        export PYTHONPATH=$GITHUB_ACTION_PATH/scripts/paramgen:$PYTHONPATH 
+        cd ${{ inputs.app_install_dir }}/run
+        python3 $GITHUB_ACTION_PATH/scripts/gen_config.py --ifile ${{ inputs.test_definition }}
+      shell: bash
 
-   # # run application
-   # - name: Run Application
-   #   run: |
-   #     export PATH=${{ inputs.dependencies_install_dir }}/view/bin:$PATH
-   #     cd ${{ inputs.app_install_dir }}/run
-   #     mpirun --oversubscribe -np 6 --allow-run-as-root ${{ inputs.app_install_dir }}/build/esmx 2>&1 | tee out_err.txt
-   #   shell: bash
+    # run application
+    - name: Run Application
+      run: |
+        export PATH=${{ inputs.dependencies_install_dir }}/view/bin:$PATH
+        cd ${{ inputs.app_install_dir }}/run
+        mpirun --oversubscribe -np 6 --allow-run-as-root ${{ inputs.app_install_dir }}/build/esmx 2>&1 | tee out_err.txt
+      shell: bash
 
-   # # upload model artifacts to check it later
-   # - name: Upload Artifacts
-   #   uses: actions/upload-artifact@v3
-   #   with:
-   #     name: artifacts for ${{ github.workflow }}
-   #     path: ${{ inputs.artifacts_files }}
-   #     retention-days: ${{ inputs.artifacts_retention_period }}
+    # upload model artifacts to check it later
+    - name: Upload Artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: artifacts for ${{ github.workflow }}
+        path: ${{ inputs.artifacts_files }}
+        retention-days: ${{ inputs.artifacts_retention_period }}
 
     # find baseline date from cache, the most recent baseline will be picked
     - name: Query Date for Old Baseline From Cache
       id: get-bl-previous 
-      if: ${{ inputs.baseline_files }} != 'None'
       run: |
         # get date for old baseline
         BL_DATE_OLD=$(gh api -H "Accept: application/vnd.github+json" \
@@ -215,79 +214,78 @@ runs:
       shell: bash
 
     # calculate hashes
-    #- name: Calculate Hashes of Output Files and Query Baseline Date
-    #  id: calculate-hashes
-    #  if: ${{ inputs.baseline_files }} != 'None'
-    #  run: |
-    #    # get current baseline date
-    #    BL_DATE_OLD=${{ steps.get-bl-previous.outputs.BL_DATE_OLD }}
-    #    # set new baseline date if 'Baseline Change' tag in PR
-    #    force_bc=${{ contains(github.event.pull_request.labels.*.name, 'Baseline Change') }}
-    #    echo "Baseline change request is force_bc = $force_bc"
-    #    if [[ "$force_bc" == "true" ]]; then
-    #      BL_DATE_NEW=$(date -u '+%Y-%m-%dT%I:%M:%S.%NZ')
-    #    else
-    #      BL_DATE_NEW=$BL_DATE_OLD
-    #    fi
-    #    echo "BL_DATE_NEW=$BL_DATE_NEW" >> $GITHUB_OUTPUT
-    #    # save hashes of output files for current run
-    #    ls -al ${{ inputs.app_install_dir }}/run
-    #    for i in $(echo "${{ inputs.baseline_files }}" | awk '$1=$1' RS= OFS=" ")
-    #    do
-    #      if echo x"$i" | grep '*' > /dev/null; then
-    #        lst2=`ls -al $i | awk '{print $9}'`
-    #        for j in $lst2; do
-    #          md5sum $j >> output_hash.txt
-    #        done
-    #      else
-    #        md5sum $i >> output_hash.txt
-    #      fi
-    #    done
-    #    # print out some debug information
-    #    if [[ "$BL_DATE_OLD" == "$BL_DATE_NEW" ]]; then
-    #      echo "BL_DATE_OLD = $BL_DATE_OLD"
-    #      echo "BL_DATE_NEW = $BL_DATE_NEW"
-    #    else
-    #      echo "Force baseline change! BL_DATE_OLD ($BL_DATE_OLD) =! BL_DATE_NEW ($BL_DATE_NEW)"
-    #    fi
-    #  shell: bash
+    - name: Calculate Hashes of Output Files and Query Baseline Date
+      id: calculate-hashes
+      run: |
+        # get current baseline date
+        BL_DATE_OLD=${{ steps.get-bl-previous.outputs.BL_DATE_OLD }}
+        # set new baseline date if 'Baseline Change' tag in PR
+        force_bc=${{ contains(github.event.pull_request.labels.*.name, 'Baseline Change') }}
+        echo "Baseline change request is force_bc = $force_bc"
+        if [[ "$force_bc" == "true" ]]; then
+          BL_DATE_NEW=$(date -u '+%Y-%m-%dT%I:%M:%S.%NZ')
+        else
+          BL_DATE_NEW=$BL_DATE_OLD
+        fi
+        echo "BL_DATE_NEW=$BL_DATE_NEW" >> $GITHUB_OUTPUT
+        # save hashes of output files for current run
+        ls -al ${{ inputs.app_install_dir }}/run
+        for i in $(echo "${{ inputs.baseline_files }}" | awk '$1=$1' RS= OFS=" ")
+        do
+          if echo x"$i" | grep '*' > /dev/null; then
+            lst2=`ls -al $i | awk '{print $9}'`
+            for j in $lst2; do
+              md5sum $j >> output_hash.txt
+            done
+          else
+            md5sum $i >> output_hash.txt
+          fi
+        done
+        # print out some debug information
+        if [[ "$BL_DATE_OLD" == "$BL_DATE_NEW" ]]; then
+          echo "BL_DATE_OLD = $BL_DATE_OLD"
+          echo "BL_DATE_NEW = $BL_DATE_NEW"
+        else
+          echo "Force baseline change! BL_DATE_OLD ($BL_DATE_OLD) =! BL_DATE_NEW ($BL_DATE_NEW)"
+        fi
+      shell: bash
 
-    ## restore baseline hash file and files from cache
-    #- name: Restore Baseline Hash File From Cache
-    #  uses: actions/cache@v3
-    #  with:
-    #    path: |
-    #      ${{ inputs.app_install_dir }}/run/output_hash_baseline.txt
-    #    key: baseline-${{ steps.calculate-hashes.outputs.BL_DATE_NEW }}
-    #    restore-keys: |
-    #      baseline-${{ steps.calculate-hashes.outputs.BL_DATE_NEW }}
+    # restore baseline hash file and files from cache
+    - name: Restore Baseline Hash File From Cache
+      uses: actions/cache@v3
+      with:
+        path: |
+          ${{ inputs.app_install_dir }}/run/output_hash_baseline.txt
+        key: baseline-${{ steps.calculate-hashes.outputs.BL_DATE_NEW }}
+        restore-keys: |
+          baseline-${{ steps.calculate-hashes.outputs.BL_DATE_NEW }}
 
-    ## compare with the baseline
-    #- name: Compare with Baseline or Create New One
-    #  id: compare-baseline
-    #  run: |
-    #    cd ${{ github.workspace }}/app/run
-    #    # compare against the baseline, returns false if it does not match
-    #    if [ -f "output_hash_baseline.txt" ]; then
-    #      echo "Baseline:"
-    #      cat output_hash_baseline.txt
-    #      echo "Current Run:"
-    #      cat output_hash.txt
-    #      echo "CHECK_RESULT=$(cmp --silent output_hash_baseline.txt output_hash.txt && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
-    #    # there is no baseline, just copy current one as baseline  
-    #    else
-    #      echo "Current run will be used as a baseline."
-    #      # print out content of the has file
-    #      cat output_hash.txt
-    #      cp output_hash.txt output_hash_baseline.txt
-    #      echo "CHECK_RESULT=$(echo 'true')" >> $GITHUB_OUTPUT
-    #    fi
-    #  shell: bash
+    # compare with the baseline
+    - name: Compare with Baseline or Create New One
+      id: compare-baseline
+      run: |
+        cd ${{ github.workspace }}/app/run
+        # compare against the baseline, returns false if it does not match
+        if [ -f "output_hash_baseline.txt" ]; then
+          echo "Baseline:"
+          cat output_hash_baseline.txt
+          echo "Current Run:"
+          cat output_hash.txt
+          echo "CHECK_RESULT=$(cmp --silent output_hash_baseline.txt output_hash.txt && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
+        # there is no baseline, just copy current one as baseline  
+        else
+          echo "Current run will be used as a baseline."
+          # print out content of the has file
+          cat output_hash.txt
+          cp output_hash.txt output_hash_baseline.txt
+          echo "CHECK_RESULT=$(echo 'true')" >> $GITHUB_OUTPUT
+        fi
+      shell: bash
 
-    ## Force to fail if the results are not matched with the baseline
-    #- name: Result of Baseline Check
-    #  if: steps.compare-baseline.outputs.CHECK_RESULT == 'false'
-    #  uses: actions/github-script@v3
-    #  with:
-    #    script: |
-    #      core.setFailed('The results do not match with the baseline!')
+    # Force to fail if the results are not matched with the baseline
+    - name: Result of Baseline Check
+      if: steps.compare-baseline.outputs.CHECK_RESULT == 'false'
+      uses: actions/github-script@v3
+      with:
+        script: |
+          core.setFailed('The results do not match with the baseline!')
